/*
Rule Engine API

A robust rule engine microservice for IoT automation. Allows users to create and manage custom automation rules with Lua script execution in a secure sandboxed environment.

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ruleengine

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiCreateActionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiCreateActionRequest{}

// ApiCreateActionRequest struct for ApiCreateActionRequest
type ApiCreateActionRequest struct {
	Enabled *bool `json:"enabled,omitempty"`
	LuaScript string `json:"lua_script"`
}

type _ApiCreateActionRequest ApiCreateActionRequest

// NewApiCreateActionRequest instantiates a new ApiCreateActionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiCreateActionRequest(luaScript string) *ApiCreateActionRequest {
	this := ApiCreateActionRequest{}
	this.LuaScript = luaScript
	return &this
}

// NewApiCreateActionRequestWithDefaults instantiates a new ApiCreateActionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiCreateActionRequestWithDefaults() *ApiCreateActionRequest {
	this := ApiCreateActionRequest{}
	return &this
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *ApiCreateActionRequest) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCreateActionRequest) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *ApiCreateActionRequest) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *ApiCreateActionRequest) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetLuaScript returns the LuaScript field value
func (o *ApiCreateActionRequest) GetLuaScript() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LuaScript
}

// GetLuaScriptOk returns a tuple with the LuaScript field value
// and a boolean to check if the value has been set.
func (o *ApiCreateActionRequest) GetLuaScriptOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LuaScript, true
}

// SetLuaScript sets field value
func (o *ApiCreateActionRequest) SetLuaScript(v string) {
	o.LuaScript = v
}

func (o ApiCreateActionRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiCreateActionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	toSerialize["lua_script"] = o.LuaScript
	return toSerialize, nil
}

func (o *ApiCreateActionRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"lua_script",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiCreateActionRequest := _ApiCreateActionRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiCreateActionRequest)

	if err != nil {
		return err
	}

	*o = ApiCreateActionRequest(varApiCreateActionRequest)

	return err
}

type NullableApiCreateActionRequest struct {
	value *ApiCreateActionRequest
	isSet bool
}

func (v NullableApiCreateActionRequest) Get() *ApiCreateActionRequest {
	return v.value
}

func (v *NullableApiCreateActionRequest) Set(val *ApiCreateActionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiCreateActionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiCreateActionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiCreateActionRequest(val *ApiCreateActionRequest) *NullableApiCreateActionRequest {
	return &NullableApiCreateActionRequest{value: val, isSet: true}
}

func (v NullableApiCreateActionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiCreateActionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


