/*
Rule Engine API

A robust rule engine microservice for IoT automation. Allows users to create and manage custom automation rules with Lua script execution in a secure sandboxed environment.

API version: 1.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ruleengine

import (
	"encoding/json"
)

// checks if the AnalyticsExecutionStats type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AnalyticsExecutionStats{}

// AnalyticsExecutionStats struct for AnalyticsExecutionStats
type AnalyticsExecutionStats struct {
	AverageLatencyMs *float32 `json:"average_latency_ms,omitempty"`
	FailedExecutions *int32 `json:"failed_executions,omitempty"`
	SuccessRate *float32 `json:"success_rate,omitempty"`
	SuccessfulExecutions *int32 `json:"successful_executions,omitempty"`
	TotalExecutions *int32 `json:"total_executions,omitempty"`
}

// NewAnalyticsExecutionStats instantiates a new AnalyticsExecutionStats object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAnalyticsExecutionStats() *AnalyticsExecutionStats {
	this := AnalyticsExecutionStats{}
	return &this
}

// NewAnalyticsExecutionStatsWithDefaults instantiates a new AnalyticsExecutionStats object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAnalyticsExecutionStatsWithDefaults() *AnalyticsExecutionStats {
	this := AnalyticsExecutionStats{}
	return &this
}

// GetAverageLatencyMs returns the AverageLatencyMs field value if set, zero value otherwise.
func (o *AnalyticsExecutionStats) GetAverageLatencyMs() float32 {
	if o == nil || IsNil(o.AverageLatencyMs) {
		var ret float32
		return ret
	}
	return *o.AverageLatencyMs
}

// GetAverageLatencyMsOk returns a tuple with the AverageLatencyMs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnalyticsExecutionStats) GetAverageLatencyMsOk() (*float32, bool) {
	if o == nil || IsNil(o.AverageLatencyMs) {
		return nil, false
	}
	return o.AverageLatencyMs, true
}

// HasAverageLatencyMs returns a boolean if a field has been set.
func (o *AnalyticsExecutionStats) HasAverageLatencyMs() bool {
	if o != nil && !IsNil(o.AverageLatencyMs) {
		return true
	}

	return false
}

// SetAverageLatencyMs gets a reference to the given float32 and assigns it to the AverageLatencyMs field.
func (o *AnalyticsExecutionStats) SetAverageLatencyMs(v float32) {
	o.AverageLatencyMs = &v
}

// GetFailedExecutions returns the FailedExecutions field value if set, zero value otherwise.
func (o *AnalyticsExecutionStats) GetFailedExecutions() int32 {
	if o == nil || IsNil(o.FailedExecutions) {
		var ret int32
		return ret
	}
	return *o.FailedExecutions
}

// GetFailedExecutionsOk returns a tuple with the FailedExecutions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnalyticsExecutionStats) GetFailedExecutionsOk() (*int32, bool) {
	if o == nil || IsNil(o.FailedExecutions) {
		return nil, false
	}
	return o.FailedExecutions, true
}

// HasFailedExecutions returns a boolean if a field has been set.
func (o *AnalyticsExecutionStats) HasFailedExecutions() bool {
	if o != nil && !IsNil(o.FailedExecutions) {
		return true
	}

	return false
}

// SetFailedExecutions gets a reference to the given int32 and assigns it to the FailedExecutions field.
func (o *AnalyticsExecutionStats) SetFailedExecutions(v int32) {
	o.FailedExecutions = &v
}

// GetSuccessRate returns the SuccessRate field value if set, zero value otherwise.
func (o *AnalyticsExecutionStats) GetSuccessRate() float32 {
	if o == nil || IsNil(o.SuccessRate) {
		var ret float32
		return ret
	}
	return *o.SuccessRate
}

// GetSuccessRateOk returns a tuple with the SuccessRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnalyticsExecutionStats) GetSuccessRateOk() (*float32, bool) {
	if o == nil || IsNil(o.SuccessRate) {
		return nil, false
	}
	return o.SuccessRate, true
}

// HasSuccessRate returns a boolean if a field has been set.
func (o *AnalyticsExecutionStats) HasSuccessRate() bool {
	if o != nil && !IsNil(o.SuccessRate) {
		return true
	}

	return false
}

// SetSuccessRate gets a reference to the given float32 and assigns it to the SuccessRate field.
func (o *AnalyticsExecutionStats) SetSuccessRate(v float32) {
	o.SuccessRate = &v
}

// GetSuccessfulExecutions returns the SuccessfulExecutions field value if set, zero value otherwise.
func (o *AnalyticsExecutionStats) GetSuccessfulExecutions() int32 {
	if o == nil || IsNil(o.SuccessfulExecutions) {
		var ret int32
		return ret
	}
	return *o.SuccessfulExecutions
}

// GetSuccessfulExecutionsOk returns a tuple with the SuccessfulExecutions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnalyticsExecutionStats) GetSuccessfulExecutionsOk() (*int32, bool) {
	if o == nil || IsNil(o.SuccessfulExecutions) {
		return nil, false
	}
	return o.SuccessfulExecutions, true
}

// HasSuccessfulExecutions returns a boolean if a field has been set.
func (o *AnalyticsExecutionStats) HasSuccessfulExecutions() bool {
	if o != nil && !IsNil(o.SuccessfulExecutions) {
		return true
	}

	return false
}

// SetSuccessfulExecutions gets a reference to the given int32 and assigns it to the SuccessfulExecutions field.
func (o *AnalyticsExecutionStats) SetSuccessfulExecutions(v int32) {
	o.SuccessfulExecutions = &v
}

// GetTotalExecutions returns the TotalExecutions field value if set, zero value otherwise.
func (o *AnalyticsExecutionStats) GetTotalExecutions() int32 {
	if o == nil || IsNil(o.TotalExecutions) {
		var ret int32
		return ret
	}
	return *o.TotalExecutions
}

// GetTotalExecutionsOk returns a tuple with the TotalExecutions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnalyticsExecutionStats) GetTotalExecutionsOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalExecutions) {
		return nil, false
	}
	return o.TotalExecutions, true
}

// HasTotalExecutions returns a boolean if a field has been set.
func (o *AnalyticsExecutionStats) HasTotalExecutions() bool {
	if o != nil && !IsNil(o.TotalExecutions) {
		return true
	}

	return false
}

// SetTotalExecutions gets a reference to the given int32 and assigns it to the TotalExecutions field.
func (o *AnalyticsExecutionStats) SetTotalExecutions(v int32) {
	o.TotalExecutions = &v
}

func (o AnalyticsExecutionStats) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AnalyticsExecutionStats) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AverageLatencyMs) {
		toSerialize["average_latency_ms"] = o.AverageLatencyMs
	}
	if !IsNil(o.FailedExecutions) {
		toSerialize["failed_executions"] = o.FailedExecutions
	}
	if !IsNil(o.SuccessRate) {
		toSerialize["success_rate"] = o.SuccessRate
	}
	if !IsNil(o.SuccessfulExecutions) {
		toSerialize["successful_executions"] = o.SuccessfulExecutions
	}
	if !IsNil(o.TotalExecutions) {
		toSerialize["total_executions"] = o.TotalExecutions
	}
	return toSerialize, nil
}

type NullableAnalyticsExecutionStats struct {
	value *AnalyticsExecutionStats
	isSet bool
}

func (v NullableAnalyticsExecutionStats) Get() *AnalyticsExecutionStats {
	return v.value
}

func (v *NullableAnalyticsExecutionStats) Set(val *AnalyticsExecutionStats) {
	v.value = val
	v.isSet = true
}

func (v NullableAnalyticsExecutionStats) IsSet() bool {
	return v.isSet
}

func (v *NullableAnalyticsExecutionStats) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAnalyticsExecutionStats(val *AnalyticsExecutionStats) *NullableAnalyticsExecutionStats {
	return &NullableAnalyticsExecutionStats{value: val, isSet: true}
}

func (v NullableAnalyticsExecutionStats) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAnalyticsExecutionStats) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


