version: '3.8'

services:
  postgres-test:
    image: postgres:15-alpine
    container_name: rule-engine-postgres-test
    environment:
      POSTGRES_DB: rule_engine_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"  # Use different port to avoid conflicts with dev DB
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
      - ../../internal/storage/db/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d rule_engine_test"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_test_data: