FROM golang:1.24.0-alpine3.17 AS builder

WORKDIR /app
COPY . .

RUN go mod download
RUN go build -o rule-engine cmd/main.go

FROM alpine:3.17

WORKDIR /app
COPY --from=builder /app/rule-engine .

CMD ["./rule-engine"]
