# coding: utf-8

"""
    Rule Engine API

    A robust rule engine microservice for IoT automation. Allows users to create and manage custom automation rules with Lua script execution in a secure sandboxed environment.

    The version of the OpenAPI document: 1.0
    Contact: support@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rule_engine_client.api.actions_api import ActionsApi


class TestActionsApi(unittest.TestCase):
    """ActionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ActionsApi()

    def tearDown(self) -> None:
        pass

    def test_actions_get(self) -> None:
        """Test case for actions_get

        List all actions
        """
        pass

    def test_actions_id_get(self) -> None:
        """Test case for actions_id_get

        Get action by ID
        """
        pass

    def test_actions_post(self) -> None:
        """Test case for actions_post

        Create a new action
        """
        pass


if __name__ == '__main__':
    unittest.main()
