# coding: utf-8

"""
    Rule Engine API

    A robust rule engine microservice for IoT automation. Allows users to create and manage custom automation rules with Lua script execution in a secure sandboxed environment.

    The version of the OpenAPI document: 1.0
    Contact: support@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rule_engine_client.api.triggers_api import TriggersApi


class TestTriggersApi(unittest.TestCase):
    """TriggersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TriggersApi()

    def tearDown(self) -> None:
        pass

    def test_triggers_get(self) -> None:
        """Test case for triggers_get

        List all triggers
        """
        pass

    def test_triggers_id_get(self) -> None:
        """Test case for triggers_id_get

        Get trigger by ID
        """
        pass

    def test_triggers_post(self) -> None:
        """Test case for triggers_post

        Create a new trigger
        """
        pass


if __name__ == '__main__':
    unittest.main()
