# coding: utf-8

"""
    Rule Engine API

    A robust rule engine microservice for IoT automation. Allows users to create and manage custom automation rules with Lua script execution in a secure sandboxed environment.

    The version of the OpenAPI document: 1.0
    Contact: support@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rule_engine_client.api.rules_api import RulesApi


class TestRulesApi(unittest.TestCase):
    """RulesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RulesApi()

    def tearDown(self) -> None:
        pass

    def test_rules_get(self) -> None:
        """Test case for rules_get

        List all rules
        """
        pass

    def test_rules_id_delete(self) -> None:
        """Test case for rules_id_delete

        Delete rule
        """
        pass

    def test_rules_id_get(self) -> None:
        """Test case for rules_id_get

        Get rule by ID
        """
        pass

    def test_rules_id_put(self) -> None:
        """Test case for rules_id_put

        Update rule
        """
        pass

    def test_rules_post(self) -> None:
        """Test case for rules_post

        Create a new rule
        """
        pass


if __name__ == '__main__':
    unittest.main()
