# coding: utf-8

"""
    Rule Engine API

    A robust rule engine microservice for IoT automation. Allows users to create and manage custom automation rules with Lua script execution in a secure sandboxed environment.

    The version of the OpenAPI document: 1.0
    Contact: support@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rule_engine_client.models.api_action_dto import ApiActionDTO

class TestApiActionDTO(unittest.TestCase):
    """ApiActionDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiActionDTO:
        """Test ApiActionDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiActionDTO`
        """
        model = ApiActionDTO()
        if include_optional:
            return ApiActionDTO(
                created_at = '',
                enabled = True,
                id = '',
                lua_script = '',
                updated_at = ''
            )
        else:
            return ApiActionDTO(
        )
        """

    def testApiActionDTO(self):
        """Test ApiActionDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
