# coding: utf-8

"""
    Rule Engine API

    A robust rule engine microservice for IoT automation. Allows users to create and manage custom automation rules with Lua script execution in a secure sandboxed environment.

    The version of the OpenAPI document: 1.0
    Contact: support@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rule_engine_client.models.api_create_trigger_request import ApiCreateTriggerRequest

class TestApiCreateTriggerRequest(unittest.TestCase):
    """ApiCreateTriggerRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiCreateTriggerRequest:
        """Test ApiCreateTriggerRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiCreateTriggerRequest`
        """
        model = ApiCreateTriggerRequest()
        if include_optional:
            return ApiCreateTriggerRequest(
                condition_script = 'if event.device_id == 'sensor_1' then return true end',
                enabled = True,
                rule_id = '550e8400-e29b-41d4-a716-446655440000',
                type = 'CONDITIONAL'
            )
        else:
            return ApiCreateTriggerRequest(
                condition_script = 'if event.device_id == 'sensor_1' then return true end',
                rule_id = '550e8400-e29b-41d4-a716-446655440000',
                type = 'CONDITIONAL',
        )
        """

    def testApiCreateTriggerRequest(self):
        """Test ApiCreateTriggerRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
