name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download dependencies
        run: go mod download

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build container for integration tests
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./containers/Containerfile
          push: false
          tags: rule-engine:local
          load: true

      - name: Run Unit tests
        run: go test -race -coverprofile=coverage.out $(go list ./... | grep -v tests)

      - name: Run E2E tests
        run: go test ./tests/e2e/...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.out

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"

      - name: Build
        run: go build -o rule-engine cmd/main.go

  container:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build container
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./containers/Containerfile
          push: false
          tags: rule-engine:test
